const allOriginalGalleryItems = [
  {
    src: "/images/gallery/originals/2026-07-12-surgical-portrait.jpg",
    originalFilename: "2026-07-12 (4).jpg",
    alt: "Dr. Kishan Rao in surgical scrubs",
    label: "Surgical portrait",
    layout: "portrait",
    objectPosition: "50% 12%",
    dimensions: "896x1000",
    orientation: "portrait",
    subject: "Solo surgical portrait",
    suitability: "Strong for gallery preview, services and clinical content",
    consentReviewRequired: false,
    hasEmbeddedText: false,
  },
  {
    src: "/images/gallery/originals/2025-11-03-clinic-consultation.jpg",
    originalFilename: "2025-11-03.jpg",
    alt: "Dr. Kishan Rao during a professional consultation",
    label: "Professional consultation",
    layout: "portrait",
    objectPosition: "50% 12%",
    dimensions: "1513x2017",
    orientation: "portrait",
    subject: "Clinic consultation",
    suitability: "Strong for gallery preview and patient-trust content",
    consentReviewRequired: true,
    hasEmbeddedText: false,
  },
  {
    src: "/images/gallery/originals/2026-02-23-operation-theatre-team.jpg",
    originalFilename: "2026-02-23 (6).jpg",
    alt: "Dr. Kishan Rao in an operation theatre setting",
    label: "Operation theatre",
    layout: "wide",
    objectPosition: "50% 25%",
    dimensions: "1030x591",
    orientation: "landscape",
    subject: "Operation theatre with medical team",
    suitability: "Useful for surgical and day-care content, moderate resolution",
    consentReviewRequired: true,
    hasEmbeddedText: false,
  },
  {
    src: "/images/gallery/originals/2026-05-25-large-audience-talk.jpg",
    originalFilename: "2026-05-25 (1).jpg",
    alt: "Dr. Kishan Rao speaking to a large audience",
    label: "Medical education talk",
    layout: "wide",
    objectPosition: "50% 25%",
    dimensions: "1513x894",
    orientation: "landscape",
    subject: "Large audience education programme",
    suitability: "Strong for education and public-speaking context",
    consentReviewRequired: true,
    hasEmbeddedText: false,
  },
  {
    src: "/images/gallery/originals/2026-02-23-scrubs-colleague.jpg",
    originalFilename: "2026-02-23 (4).jpg",
    alt: "Dr. Kishan Rao in surgical attire with a colleague",
    label: "Surgical practice",
    layout: "portrait",
    objectPosition: "50% 12%",
    dimensions: "1513x1941",
    orientation: "portrait",
    subject: "Surgical attire with colleague",
    suitability: "Strong for surgical sections",
    consentReviewRequired: true,
    hasEmbeddedText: false,
  },
  {
    src: "/images/gallery/originals/2026-07-12-clinical-consultation.jpg",
    originalFilename: "2026-07-12 (1).jpg",
    alt: "Dr. Kishan Rao during a clinical consultation",
    label: "Clinical consultation",
    layout: "portrait",
    objectPosition: "50% 10%",
    dimensions: "896x1185",
    orientation: "portrait",
    subject: "Clinical consultation with patient",
    suitability: "Good gallery image; consent review needed before prominent reuse",
    consentReviewRequired: true,
    hasEmbeddedText: false,
  },
  {
    src: "/images/gallery/originals/2025-11-03-speaking-award.jpg",
    originalFilename: "2025-11-03 (1).jpg",
    alt: "Dr. Kishan Rao speaking on stage",
    label: "Stage address",
    layout: "wide",
    objectPosition: "50% 22%",
    dimensions: "1513x1009",
    orientation: "landscape",
    subject: "Solo stage address",
    suitability: "Good for public-speaking context",
    consentReviewRequired: false,
    hasEmbeddedText: false,
  },
  {
    src: "/images/gallery/originals/2026-06-24-surgical-conference.jpg",
    originalFilename: "2026-06-24 (1).jpg",
    alt: "Dr. Kishan Rao at a surgical conference",
    label: "Surgical conference",
    layout: "portrait",
    objectPosition: "50% 12%",
    dimensions: "1513x2017",
    orientation: "portrait",
    subject: "Surgical conference with colleagues",
    suitability: "Good for professional gallery and surgical blog context",
    consentReviewRequired: true,
    hasEmbeddedText: false,
  },
  {
    src: "/images/gallery/originals/2025-11-03-stage-felicitation.jpg",
    originalFilename: "2025-11-03 (2).jpg",
    alt: "Dr. Kishan Rao receiving recognition on stage",
    label: "Recognition ceremony",
    layout: "portrait",
    objectPosition: "50% 12%",
    dimensions: "1513x2017",
    orientation: "portrait",
    subject: "Stage felicitation",
    suitability: "Good for recognitions archive",
    consentReviewRequired: true,
    hasEmbeddedText: false,
  },
  {
    src: "/images/gallery/originals/2026-02-23-award-group.jpg",
    originalFilename: "2026-02-23 (1).jpg",
    alt: "Dr. Kishan Rao with award recipients at an event",
    label: "Award event",
    layout: "wide",
    objectPosition: "50% 25%",
    dimensions: "1035x639",
    orientation: "landscape",
    subject: "Award group photograph",
    suitability: "Archive use; moderate resolution",
    consentReviewRequired: true,
    hasEmbeddedText: false,
  },
  {
    src: "/images/gallery/originals/2026-02-23-felicitation-portrait.jpg",
    originalFilename: "2026-02-23 (2).jpg",
    alt: "Dr. Kishan Rao during a felicitation ceremony",
    label: "Felicitation moment",
    layout: "portrait",
    objectPosition: "50% 12%",
    dimensions: "525x743",
    orientation: "portrait",
    subject: "Felicitation ceremony",
    suitability: "Archive use only because of lower resolution",
    consentReviewRequired: true,
    hasEmbeddedText: false,
  },
  {
    src: "/images/gallery/originals/2026-02-23-honour-ceremony.jpg",
    originalFilename: "2026-02-23 (3).jpg",
    alt: "Dr. Kishan Rao being honoured at an event",
    label: "Honour ceremony",
    layout: "portrait",
    objectPosition: "50% 12%",
    dimensions: "821x1002",
    orientation: "portrait",
    subject: "Honour ceremony",
    suitability: "Archive use",
    consentReviewRequired: true,
    hasEmbeddedText: false,
  },
  {
    src: "/images/gallery/originals/2026-02-23-community-stage-talk.jpg",
    originalFilename: "2026-02-23 (5).jpg",
    alt: "Dr. Kishan Rao speaking at a community programme",
    label: "Community programme",
    layout: "wide",
    objectPosition: "50% 22%",
    dimensions: "1280x960",
    orientation: "landscape",
    subject: "Community stage talk",
    suitability: "Good for social/community archive",
    consentReviewRequired: true,
    hasEmbeddedText: true,
  },
  {
    src: "/images/gallery/originals/2026-02-23-office-recognition.jpg",
    originalFilename: "2026-02-23 (7).jpg",
    alt: "Dr. Kishan Rao presenting a recognition certificate",
    label: "Office recognition",
    layout: "wide",
    objectPosition: "50% 16%",
    dimensions: "1513x1439",
    orientation: "landscape",
    subject: "Office recognition photograph",
    suitability: "Good archive image",
    consentReviewRequired: true,
    hasEmbeddedText: false,
  },
  {
    src: "/images/gallery/originals/2026-02-23-child-consultation.jpg",
    originalFilename: "2026-02-23 (8).jpg",
    alt: "Dr. Kishan Rao with a child during a consultation setting",
    label: "Consultation moment",
    layout: "portrait",
    objectPosition: "50% 10%",
    dimensions: "576x1280",
    orientation: "portrait",
    subject: "Child consultation setting",
    suitability: "Archive use; consent review required",
    consentReviewRequired: true,
    hasEmbeddedText: false,
  },
  {
    src: "/images/gallery/originals/2026-02-23-doctor-talk-slide.jpg",
    originalFilename: "2026-02-23 (9).jpg",
    alt: "Dr. Kishan Rao delivering a doctor-patient communication talk",
    label: "Doctor talk",
    layout: "wide",
    objectPosition: "50% 18%",
    dimensions: "575x468",
    orientation: "landscape",
    subject: "Doctor communication talk",
    suitability: "Archive use only because of lower resolution",
    consentReviewRequired: false,
    hasEmbeddedText: true,
  },
  {
    src: "/images/gallery/originals/2026-02-23-child-patient-collage.jpg",
    originalFilename: "2026-02-23.jpg",
    alt: "Collage of Dr. Kishan Rao with children in care settings",
    label: "Care moments",
    layout: "wide",
    objectPosition: "50% 22%",
    dimensions: "1513x1513",
    orientation: "square",
    subject: "Collage with children",
    suitability: "Archive use; not for prominent reuse",
    consentReviewRequired: true,
    hasEmbeddedText: true,
  },
  {
    src: "/images/gallery/originals/2026-04-14-teacher-recognition.jpg",
    originalFilename: "2026-04-14.jpg",
    alt: "Dr. Kishan Rao with a teacher and recognition certificate",
    label: "Teacher recognition",
    layout: "portrait",
    objectPosition: "50% 12%",
    dimensions: "650x862",
    orientation: "portrait",
    subject: "Teacher recognition photograph",
    suitability: "Archive use; lower resolution",
    consentReviewRequired: true,
    hasEmbeddedText: true,
  },
  {
    src: "/images/gallery/originals/2026-05-01-health-awareness-session.jpg",
    originalFilename: "2026-05-01 (1).jpg",
    alt: "Dr. Kishan Rao presenting at a health awareness session",
    label: "Health awareness session",
    layout: "wide",
    objectPosition: "50% 25%",
    dimensions: "960x850",
    orientation: "landscape",
    subject: "Community health awareness session",
    suitability: "Good for social initiatives archive",
    consentReviewRequired: true,
    hasEmbeddedText: true,
  },
  {
    src: "/images/gallery/originals/2026-05-01-community-presentation.jpg",
    originalFilename: "2026-05-01 (2).jpg",
    alt: "Dr. Kishan Rao giving a community presentation",
    label: "Community presentation",
    layout: "wide",
    objectPosition: "50% 25%",
    dimensions: "917x858",
    orientation: "landscape",
    subject: "Community presentation",
    suitability: "Archive use; near-duplicate of another session image",
    consentReviewRequired: true,
    hasEmbeddedText: true,
  },
  {
    src: "/images/gallery/originals/2026-05-01-stage-recognition.jpg",
    originalFilename: "2026-05-01 (3).jpg",
    alt: "Dr. Kishan Rao at a stage recognition event",
    label: "Stage recognition",
    layout: "wide",
    objectPosition: "50% 25%",
    dimensions: "762x542",
    orientation: "landscape",
    subject: "Stage recognition",
    suitability: "Archive use",
    consentReviewRequired: true,
    hasEmbeddedText: true,
  },
  {
    src: "/images/gallery/originals/2026-05-01-medical-education-talk.jpg",
    originalFilename: "2026-05-01.jpg",
    alt: "Dr. Kishan Rao speaking at a medical education session",
    label: "Medical education session",
    layout: "wide",
    objectPosition: "50% 25%",
    dimensions: "793x578",
    orientation: "landscape",
    subject: "Medical education talk",
    suitability: "Archive use; near-duplicate of session photographs",
    consentReviewRequired: true,
    hasEmbeddedText: true,
  },
  {
    src: "/images/gallery/originals/2026-05-25-auditorium-address.jpg",
    originalFilename: "2026-05-25.jpg",
    alt: "Dr. Kishan Rao addressing an auditorium audience",
    label: "Auditorium address",
    layout: "wide",
    objectPosition: "50% 25%",
    dimensions: "1513x772",
    orientation: "landscape",
    subject: "Auditorium address",
    suitability: "Strong education archive image",
    consentReviewRequired: true,
    hasEmbeddedText: false,
  },
  {
    src: "/images/gallery/originals/2026-06-24-conference-portrait.jpg",
    originalFilename: "2026-06-24.jpg",
    alt: "Dr. Kishan Rao at a professional conference",
    label: "Professional conference",
    layout: "portrait",
    objectPosition: "50% 12%",
    dimensions: "1513x2017",
    orientation: "portrait",
    subject: "Professional conference portrait",
    suitability: "Good archive image",
    consentReviewRequired: true,
    hasEmbeddedText: false,
  },
  {
    src: "/images/gallery/originals/2026-07-12-newspaper-feature.jpg",
    originalFilename: "2026-07-12 (2).jpg",
    alt: "Newspaper feature about Dr. Kishan Rao",
    label: "Newspaper feature",
    layout: "portrait",
    objectPosition: "50% 10%",
    dimensions: "750x998",
    orientation: "portrait",
    subject: "Newspaper feature clipping",
    suitability: "Archive use",
    consentReviewRequired: false,
    hasEmbeddedText: true,
  },
  {
    src: "/images/gallery/originals/2026-07-12-best-doctor-poster.jpg",
    originalFilename: "2026-07-12 (3).jpg",
    alt: "Best Doctor Ever poster featuring Dr. Kishan Rao",
    label: "Medical department poster",
    layout: "portrait",
    objectPosition: "50% 8%",
    dimensions: "853x1280",
    orientation: "portrait",
    subject: "Medical department poster",
    suitability: "Archive use",
    consentReviewRequired: false,
    hasEmbeddedText: true,
  },
  {
    src: "/images/gallery/originals/2026-07-12-doctors-day-felicitation.jpg",
    originalFilename: "2026-07-12 (5).jpg",
    alt: "Dr. Kishan Rao at a Doctors Day felicitation",
    label: "Doctors Day felicitation",
    layout: "wide",
    objectPosition: "50% 25%",
    dimensions: "1513x1139",
    orientation: "landscape",
    subject: "Doctors Day felicitation",
    suitability: "Archive use",
    consentReviewRequired: true,
    hasEmbeddedText: false,
  },
  {
    src: "/images/gallery/originals/2026-07-12-doctors-day-stage.jpg",
    originalFilename: "2026-07-12 (6).jpg",
    alt: "Dr. Kishan Rao speaking at a Doctors Day event",
    label: "Doctors Day event",
    layout: "wide",
    objectPosition: "50% 25%",
    dimensions: "1513x1139",
    orientation: "landscape",
    subject: "Doctors Day event",
    suitability: "Archive use; near-duplicate event angle",
    consentReviewRequired: true,
    hasEmbeddedText: false,
  },
  {
    src: "/images/gallery/originals/2026-07-12-community-family-visit.jpg",
    originalFilename: "2026-07-12.jpg",
    alt: "Dr. Kishan Rao during a community visit",
    label: "Community visit",
    layout: "wide",
    objectPosition: "50% 22%",
    dimensions: "1513x1135",
    orientation: "landscape",
    subject: "Community visit with family",
    suitability: "Archive use; consent review required",
    consentReviewRequired: true,
    hasEmbeddedText: false,
  },
  {
    src: "/images/gallery/originals/2026-07-22-school-education-talk.jpg",
    originalFilename: "2026-07-22 (1).jpg",
    alt: "Dr. Kishan Rao speaking at a school education programme",
    label: "School education programme",
    layout: "wide",
    objectPosition: "50% 25%",
    dimensions: "1513x1135",
    orientation: "landscape",
    subject: "School education programme",
    suitability: "Good education archive image",
    consentReviewRequired: true,
    hasEmbeddedText: true,
  },
  {
    src: "/images/gallery/originals/2026-07-22-stage-bouquet.jpg",
    originalFilename: "2026-07-22.jpg",
    alt: "Dr. Kishan Rao receiving a bouquet on stage",
    label: "Stage recognition",
    layout: "wide",
    objectPosition: "50% 18%",
    dimensions: "1513x1316",
    orientation: "landscape",
    subject: "Stage recognition with bouquet",
    suitability: "Good recognitions archive image",
    consentReviewRequired: true,
    hasEmbeddedText: false,
  },
] as const;

const displayedGallerySources = [
  "/images/gallery/originals/2026-07-12-surgical-portrait.jpg",
  "/images/gallery/originals/2026-02-23-operation-theatre-team.jpg",
  "/images/gallery/originals/2026-02-23-scrubs-colleague.jpg",
  "/images/gallery/originals/2025-11-03-clinic-consultation.jpg",
  "/images/gallery/originals/2026-07-12-clinical-consultation.jpg",
  "/images/gallery/originals/2026-06-24-conference-portrait.jpg",
  "/images/gallery/originals/2026-05-25-large-audience-talk.jpg",
  "/images/gallery/originals/2025-11-03-speaking-award.jpg",
  "/images/gallery/originals/2026-02-23-office-recognition.jpg",
  "/images/gallery/originals/2025-11-03-stage-felicitation.jpg",
  "/images/gallery/originals/2026-07-12-doctors-day-felicitation.jpg",
  "/images/gallery/originals/2026-07-22-stage-bouquet.jpg",
  "/images/gallery/originals/2026-07-22-school-education-talk.jpg",
  "/images/gallery/originals/2026-02-23-community-stage-talk.jpg",
  "/images/gallery/originals/2026-02-23-honour-ceremony.jpg",
] as const;

export const originalGalleryItems = displayedGallerySources.map((src) => {
  const item = allOriginalGalleryItems.find((galleryItem) => galleryItem.src === src);

  if (!item) {
    throw new Error(`Missing curated gallery image: ${src}`);
  }

  return item;
});
